apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "karpenter-{{ .Values.karpenter.settings.clusterName }}" 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}

  amiSelectorTerms:
    - id: {{ .Values.karpenter.settings.amiSelector.amd }} #"ami-049e49d359c8505cc"

  tags:
    Name: "{{ .Values.karpenter.settings.clusterName }}-Karpenter-Instance"


